### ISSUE TITLE
S4 dispatching for RCM() function

### ISSUE THREAD

**Issue by sthawinke** [CenterForStatistics-UGent/RCM#1]
@JoFAM 
S4 dispatching needed for RCM() function, and possibly also for all build*Mat functions

**Comment by JoFAM** [comment]
This work is done in the branch AddS4.

**Comment by JoFAM** [comment]
@sthawinke ik ga die issues open laten staan tot dit gedaan is, zodat ik de issues als een to-do lijst kan gebruiken. OK voor jou?

**Comment by sthawinke** [comment]
Ok np
