### ISSUE TITLE
in buildCovmat, the test for factors with one level is not working

### ISSUE THREAD

**Issue by FMKerckhof** [CenterForStatistics-UGent/RCM#11]
The first if-statement tot test if a factor only contains one level is not exactly testing that, and will always return that factors with one level were dropped, if they have more than one level.

https://github.com/CenterForStatistics-UGent/RCM/blob/92db2fd801db326fe68f908d84b1089b4bc889a4/R/F_buildCovMat.R#L70

in fact, to evaluate correctly, this conditional statement should *probably* become `if(length(covariatesNames)==0){}`, but this would not be sensible given the next check, so maybe the initial definition of covariatesNames should be different? Further down the line is it meant to say that a constrained ordination with one variable is meaningless or with one level (a single variable can have more than one level)?

**Comment by sthawinke** [comment]
This was indeed nonsensical, the code has been modified and simplified. Feel free to close the issue if you believe the problem has been solved adequately.

It is indeed meant to refer to a variable with one level, the warning has been modified.

**Comment by FMKerckhof** [comment]
perfect, that works for me 👍
