### ISSUE TITLE
issue with including a confounder within the plot

### ISSUE THREAD

**Issue by Nermin-Ghith** [CenterForStatistics-UGent/RCM#17]
Hi,
I am trying this code:
CRC.rcm<-RCM(df,
              confounders="Region",round=TRUE)

but I keep getting this message:
Error in inherits(frml, "formula") : 
argument "frml" is missing, with no default

this code used to work up to one month ago. I am not sure what is problem here.
Thanks for any help.
Best,
Nermin

**Comment by sthawinke** [comment]
Hi Nermin,

Thanks for your message. I cannot immediately see the problem from my side, therefore a couple of questions to help resolve the issue:

- Do you know which version change caused the code to break? Which RCM version are you currently using?
- Do you know from which function call the error emanates?
- What is the class of 'df', is it a phyloseq object?

Any additional information you supply may help us find the bug.

Regards,

Stijn

**Comment by Nermin-Ghith** [comment]
Hi Stijn,
- I am using version 1.10.0
- I am not sure about what causes the error, but it seems that it happened when it converts to a formula. I tried to replace the confounder with another variable (income group) but I get the same error. 
-  I am using a phyloseq object

- this is the message with the show trackback:

"Error in inherits(frml, "formula") : 
argument "frml" is missing, with no default

10. model.matrix.formula(object = as.formula(paste("~", paste(names(confounders)[vapply(FUN.VALUE = TRUE, 
confounders, is.factor)], collapse = "+"), "-1")), data = confounders, 
contrasts.arg = lapply(confounders[vapply(FUN.VALUE = TRUE, 
confounders, is.factor)], contrasts, contrasts = FALSE))
9. model.matrix(object = as.formula(paste("~", paste(names(confounders)[vapply(FUN.VALUE = TRUE, 
confounders, is.factor)], collapse = "+"), "-1")), data = confounders, 
contrasts.arg = lapply(confounders[vapply(FUN.VALUE = TRUE, 
confounders, is.factor)], contrasts, contrasts = FALSE))
8. model.matrix(object = as.formula(paste("~", paste(names(confounders)[vapply(FUN.VALUE = TRUE, 
confounders, is.factor)], collapse = "+"), "-1")), data = confounders, 
contrasts.arg = lapply(confounders[vapply(FUN.VALUE = TRUE, 
confounders, is.factor)], contrasts, contrasts = FALSE))
7. buildConfMat.data.frame(confounders, n = nsamples(physeq))
6. buildConfMat(confounders, n = nsamples(physeq))
5. buildConfMat.character(confounders, dat)
4. buildConfMat(confounders, dat)
3. .local(dat, ...)
2. RCM(physeq1, confounders = "income_group", round = TRUE)
1. RCM(physeq1, confounders = "income_group", round = TRUE)

I hope that you can help me to find out what causes this error.
Best,
Nermin

**Comment by sthawinke** [comment]
Hi Nermin,

I have investigated it a bit further. I am still not sure, but it may have to do with the dependencies, and the correct version of the model.matrix function. I cannot find the model.matrix.formula or inherits(frml, "formula") online, any idea which package they are from? Could you provide the output of sessionInfo()?

Anyway, I have declared the correct stats::model.matrix version now. Could you install from github and try again?

Hope this helps,

Stijn

**Comment by Nermin-Ghith** [comment]
Hi Stiijn,
Thank you so much. You are great. The code is working now.
I do not know so far what was the problem, I hope that I can find out about it so I can handle it if it happens again.
Best,
Nermin

**Comment by sthawinke** [comment]
I am glad it worked! I'm closing the issue now
